id: IAAA0FAA9
ocr_import_info:
  timestamp: '2023-08-15T02:12:35.544948+00:00'
  batch_id: batch-ead8
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-15 02:53:10.792189+00:00
last_modified: 2023-08-15 02:53:10.792194+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W27553
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27553
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་དབྱིངས་བསྟོད་པའི་རྣམ་བཤད་སྙིང་པོ་གསལ་བ།
  languages:
  - bo
  author: སྨྱུང་གནས་བླ་མ་བསོད་ནམས་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8133191639855737
  ocr_word_median_confidence_index: 0.866406
bases:
  I4379:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4379
      total_pages: 80
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I4379.txt
    statistics:
      ocr_word_median_confidence_index: 0.866406
      ocr_word_mean_confidence_index: 0.8133191639855737
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
